#!/bin/bash

set -e

# This case checks compatibility with the code generated by the official
# protoc-gen-go, so it is generated with protoc only; the opaque and hybrid
# API levels are protoc-gen-go options that prutalgen does not have.
protoc --proto_path=. --go_out=. --go_opt=paths=source_relative compat3.proto compat2/compat2.proto compat2023/compat2023.proto
protoc --proto_path=. --go_out=. --go_opt=paths=source_relative --go_opt=default_api_level=API_OPAQUE apiopaque/api.proto
protoc --proto_path=. --go_out=. --go_opt=paths=source_relative --go_opt=default_api_level=API_HYBRID apihybrid/api.proto

go test -v
# the hybrid API takes the opaque layout under this tag, see hybridOpaque
go test -v -tags protoopaque
