header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  # third-party code that must keep its original license header
  paths-ignore:
    - 'prutalgen/internal/antlr'
    - 'prutalgen/internal/parser'
    - 'prutalgen/internal/protobuf'
    - 'internal/protowire/wire.go'
    - 'internal/protowire/wire_test.go'

  comment: on-failure
