/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by prutalgen. DO NOT EDIT.
// prutalgen --proto_path=. --go_out=../ ./testdata_edition2023.proto

package prutal

// Every way an edition 2023 field can track presence, generated by prutalgen:
// the tests check that the markers it writes drive the encoder the way
// protobuf-go serializes the same values.
type TestEdition2023Presence struct {
	ByExplicit  []byte `protobuf:"bytes,1,opt,name=by_explicit" json:"by_explicit,omitempty"`
	ByImplicit  []byte `protobuf:"bytes,2,opt,name=by_implicit,implicit" json:"by_implicit,omitempty"`
	ByRequired  []byte `protobuf:"bytes,3,req,name=by_required" json:"by_required,omitempty"`
	ByAggregate []byte `protobuf:"bytes,4,opt,name=by_aggregate,implicit" json:"by_aggregate,omitempty"`
	IExplicit   *int32 `protobuf:"varint,5,opt,name=i_explicit" json:"i_explicit,omitempty"`
	IImplicit   int32  `protobuf:"varint,6,opt,name=i_implicit,implicit" json:"i_implicit,omitempty"`
	IRequired   *int32 `protobuf:"varint,7,req,name=i_required" json:"i_required,omitempty"`
	SImplicit   string `protobuf:"bytes,8,opt,name=s_implicit,implicit" json:"s_implicit,omitempty"`
	// Types that are assignable to K:
	//
	//	*TestEdition2023Presence_ByOneof
	K      isTestEdition2023Presence_K `protobuf_oneof:"k"`
	ByList [][]byte                    `protobuf:"bytes,10,rep,name=by_list" json:"by_list,omitempty"`
}

func (x *TestEdition2023Presence) Reset() { *x = TestEdition2023Presence{} }

// XXX_OneofWrappers is for the internal use of the prutal package.
func (*TestEdition2023Presence) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestEdition2023Presence_ByOneof)(nil),
	}
}

type isTestEdition2023Presence_K interface {
	isTestEdition2023Presence_K()
}

type TestEdition2023Presence_ByOneof struct {
	ByOneof []byte `protobuf:"bytes,9,opt,name=by_oneof,oneof" json:"by_oneof,omitempty"`
}

func (*TestEdition2023Presence_ByOneof) isTestEdition2023Presence_K() {}
